services:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  pgweb:
    image: sosedoff/pgweb:0.11.12
    restart: always
    environment:
      DATABASE_URL: postgres://admin:password@postgres/app?sslmode=disable
    depends_on:
      - postgres
    ports:
      - 8081:8081
